# @name baseUrl
http://localhost:8080

# @name authToken
your_auth_token_here

# @name adminToken
your_admin_token_here

### 注册用户
POST {{baseUrl}}/register
Content-Type: application/json

{
  "user_id": "testuser",
  "password": "testpassword",
  "class": "class1",
  "grade": "grade1"
}

### 普通用户登录
POST {{baseUrl}}/login
Content-Type: application/json

{
  "user_id": "testuser",
  "password": "testpassword"
}

### 获取用户信息
GET {{baseUrl}}/user/info
Authorization: Bearer {{authToken}}

### 普通用户登录
POST {{baseUrl}}/login
Content-Type: application/json

{
  "user_id": "user111",
  "password": "pass1"
}

### 普通用户修改密码
POST {{baseUrl}}/user/change-password
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "old_password": "pass1",
  "new_password": "pass1"
}

### 注册管理员
POST {{baseUrl}}/register
Content-Type: application/json

{
  "user_id": "admin",
  "password": "adminpass",
  "is_admin": true
}

### 管理员登录
POST {{baseUrl}}/login
Content-Type: application/json

{
  "user_id": "admin",
  "password": "adminpass"
}

### 获取用户分数
GET {{baseUrl}}/user/score
Authorization: Bearer {{authToken}}

### 创建容器
POST {{baseUrl}}/container
Authorization: Bearer {{authToken}}

### 启动容器
POST {{baseUrl}}/container/start
Authorization: Bearer {{authToken}}

### 停止容器
POST {{baseUrl}}/container/stop
Authorization: Bearer {{authToken}}

### 删除容器
DELETE {{baseUrl}}/container
Authorization: Bearer {{authToken}}

### 管理员批量创建用户
POST {{baseUrl}}/admin/users/bulk-create
Authorization: Bearer {{adminToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="users.csv"
Content-Type: text/csv

user1111,pass1,class1,grade1
user2111,pass2,class2,grade2
user3111,pass3,class3,grade3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 管理员获取学生信息
GET {{baseUrl}}/admin/students/class=class1&grade=grade1&page=2&page_size=20
Authorization: Bearer {{adminToken}}

### 管理员删除用户
DELETE {{baseUrl}}/admin/user/testuser
Authorization: Bearer {{adminToken}}

### 管理员修改用户密码
// user2 替换为实际需要更改的user_id
POST {{baseUrl}}/admin/user/user2/change-password
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "new_password": "12345"
}

### 测试docker port proxy
POST http://localhost:9001/execute
Content-Type: application/x-www-form-urlencoded

cmd = ls

### socres
GET http://localhost:9001/scores